import type { DashboardData } from "./types";

export const mockData: DashboardData = {
  tasks: [
    {
      id: "t1",
      title: "Complete Cloudflare deployment for EncryptKeeper",
      source: "notion",
      project: "EncryptKeeper",
      status: "in_progress",
      priority: "high",
      dueDate: "2026-06-10",
      tags: ["deploy", "infra"],
      lastActivity: "2026-06-06",
    },
    {
      id: "t2",
      title: "Fix extraction test failures in MemoryOS",
      source: "notion",
      project: "MemoryOS",
      status: "todo",
      priority: "high",
      tags: ["bug", "testing"],
      lastActivity: "2026-05-21",
    },
    {
      id: "t3",
      title: "Phase R2-A: Thematic report types",
      source: "github",
      sourceUrl: "https://github.com/stevemikedan/genielogical/issues/1",
      project: "GenieLogical",
      status: "todo",
      priority: "medium",
      tags: ["feature"],
    },
    {
      id: "t4",
      title: "Plugin system for Alignment Lab (Phase 5)",
      source: "notion",
      project: "Alignment Lab",
      status: "todo",
      priority: "medium",
      tags: ["feature", "architecture"],
      lastActivity: "2026-05-21",
    },
    {
      id: "t5",
      title: "BCS instructor guide generator - scaffolding",
      source: "notion",
      project: "BCS",
      status: "todo",
      priority: "high",
      dueDate: "2026-06-15",
      tags: ["client", "greenfield"],
    },
    {
      id: "t6",
      title: "Discourse pattern tracking for Hatchery",
      source: "notion",
      project: "Hatchery",
      status: "in_progress",
      priority: "medium",
      tags: ["feature"],
      lastActivity: "2026-06-07",
    },
    {
      id: "t7",
      title: "MWFB Hackathon: Build Portfolio Pulse",
      source: "notion",
      project: "Portfolio Pulse",
      status: "in_progress",
      priority: "high",
      dueDate: "2026-06-12",
      tags: ["hackathon"],
      lastActivity: "2026-06-08",
    },
    {
      id: "t8",
      title: "n-site: Update toolkit page with new scrolls",
      source: "notion",
      project: "n-site",
      status: "todo",
      priority: "low",
      tags: ["content"],
    },
    {
      id: "t9",
      title: "Push react-big-schedule fork (35 commits)",
      source: "github",
      sourceUrl: "https://github.com/stevemikedan/react-big-schedule",
      project: "react-big-schedule",
      status: "blocked",
      priority: "low",
      tags: ["publish"],
      lastActivity: "2026-03-18",
    },
  ],
  activity: [
    {
      id: "a1",
      type: "commit",
      title: "feat: scaffold Portfolio Pulse with Next.js 16",
      repo: "portfolio-pulse",
      branch: "main",
      timestamp: "2026-06-08T20:00:00Z",
      matchedTaskId: "t7",
    },
    {
      id: "a2",
      type: "commit",
      title: "docs(sourcevision): dissolve link-notification-ui-widgets zone",
      repo: "belief-atlas",
      branch: "ndx",
      timestamp: "2026-06-07T18:00:00Z",
    },
    {
      id: "a3",
      type: "commit",
      title: "fix(web): fix structural findings in discussion-thread zone",
      repo: "belief-atlas",
      branch: "ndx",
      timestamp: "2026-06-07T16:30:00Z",
    },
    {
      id: "a4",
      type: "pr_merged",
      title: "Cipher toolkit Phase 1: landing + Caesar tool",
      repo: "EncryptKeeper",
      timestamp: "2026-05-21T15:00:00Z",
      matchedTaskId: "t1",
    },
    {
      id: "a5",
      type: "commit",
      title: "feat: Introduce v2 analysis outputs and data manifests",
      repo: "consolvent",
      timestamp: "2026-06-05T14:00:00Z",
    },
    {
      id: "a6",
      type: "issue_closed",
      title: "Add MCP server with 7 structured tools",
      repo: "MemoryOS",
      timestamp: "2026-05-20T12:00:00Z",
      matchedTaskId: "t2",
    },
  ],
  gaps: [
    {
      type: "neglected",
      label: "MemoryOS has no activity in 18 days",
      detail:
        "Last commit May 21. You have a high-priority task (fix extraction tests) with no recent progress.",
      severity: "danger",
      relatedTaskId: "t2",
    },
    {
      type: "unplanned",
      label: "3 hours on Belief Atlas with no open task",
      detail:
        "Recent commits to belief-atlas ndx branch don't match any tracked assignment.",
      severity: "info",
    },
    {
      type: "neglected",
      label: "BCS client project has zero commits",
      detail:
        "Due June 15. No code exists yet. High priority task with no activity.",
      severity: "warning",
      relatedTaskId: "t5",
    },
    {
      type: "overloaded",
      label: "5 projects active simultaneously",
      detail:
        "You have in-progress tasks across EncryptKeeper, Hatchery, Portfolio Pulse, Belief Atlas, and consolvent. Consider parking some.",
      severity: "warning",
    },
  ],
  rhythm: [
    { date: "2026-06-02", commits: 4, prsOpened: 1, prsMerged: 0, issuesClosed: 1 },
    { date: "2026-06-03", commits: 7, prsOpened: 0, prsMerged: 1, issuesClosed: 0 },
    { date: "2026-06-04", commits: 2, prsOpened: 0, prsMerged: 0, issuesClosed: 0 },
    { date: "2026-06-05", commits: 5, prsOpened: 1, prsMerged: 0, issuesClosed: 2 },
    { date: "2026-06-06", commits: 1, prsOpened: 0, prsMerged: 0, issuesClosed: 0 },
    { date: "2026-06-07", commits: 6, prsOpened: 0, prsMerged: 1, issuesClosed: 0 },
    { date: "2026-06-08", commits: 3, prsOpened: 0, prsMerged: 0, issuesClosed: 0 },
  ],
  stats: {
    totalTasks: 9,
    inProgress: 3,
    overdue: 0,
    finishRate: 0.35,
    activeRepos: 5,
  },
};
